
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ws.BanqueApp", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8989/?wsdl")
public class WsBanqueApp
    extends Service
{

    private static final URL WSBANQUEAPP_WSDL_LOCATION;
    private static final WebServiceException WSBANQUEAPP_EXCEPTION;
    private static final QName WSBANQUEAPP_QNAME = new QName("http://ws/", "ws.BanqueApp");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBANQUEAPP_WSDL_LOCATION = url;
        WSBANQUEAPP_EXCEPTION = e;
    }

    public WsBanqueApp() {
        super(__getWsdlLocation(), WSBANQUEAPP_QNAME);
    }

    public WsBanqueApp(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBANQUEAPP_QNAME, features);
    }

    public WsBanqueApp(URL wsdlLocation) {
        super(wsdlLocation, WSBANQUEAPP_QNAME);
    }

    public WsBanqueApp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBANQUEAPP_QNAME, features);
    }

    public WsBanqueApp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBanqueApp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueApp
     */
    @WebEndpoint(name = "BanqueAppPort")
    public BanqueApp getBanqueAppPort() {
        return super.getPort(new QName("http://ws/", "BanqueAppPort"), BanqueApp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueApp
     */
    @WebEndpoint(name = "BanqueAppPort")
    public BanqueApp getBanqueAppPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BanqueAppPort"), BanqueApp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBANQUEAPP_EXCEPTION!= null) {
            throw WSBANQUEAPP_EXCEPTION;
        }
        return WSBANQUEAPP_WSDL_LOCATION;
    }

}
